name: Deploy Function + Streamlit (SP)

on:
  push:
    branches: [main, master]
    paths:
      - "**.py"
      - "requirements.txt"
      - "host.json"
      - ".funcignore"
      - "streamlit_app/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

env:
  AZ_RG: recoprojet10rg
  FUNC_APP: recoprojet10
  WEBAPP: reco-streamlit-portal

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      functions_changed: ${{ steps.filter.outputs.functions_changed }}
      streamlit_changed: ${{ steps.filter.outputs.streamlit_changed }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            functions_changed:
              - 'function_app.py'
              - 'recommender.py'
              - 'shared.py'
              - 'host.json'
              - 'requirements.txt'
              - '.funcignore'
            streamlit_changed:
              - 'streamlit_app/**'

  deploy-functions:
    needs: detect-changes
    if: needs.detect-changes.outputs.functions_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Zip Function
        run: |
          zip -r function.zip . -x "streamlit_app/*" ".git/*" ".github/*" "__pycache__/*" "*.ipynb_checkpoints/*"

      - name: Deploy Function (zip deploy)
        run: |
          az functionapp deployment source config-zip \
            --resource-group $AZ_RG \
            --name $FUNC_APP \
            --src function.zip

  deploy-streamlit:
    needs: detect-changes
    if: needs.detect-changes.outputs.streamlit_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Zip Streamlit
        run: |
          cd streamlit_app
          zip -r ../streamlit.zip .

      - name: First-time app settings (idempotent)
        run: |
          az webapp config appsettings set \
            --resource-group $AZ_RG \
            --name $WEBAPP \
            --settings SCM_DO_BUILD_DURING_DEPLOYMENT=1

      - name: Deploy Streamlit (zip deploy)
        run: |
          az webapp deployment source config-zip \
            --resource-group $AZ_RG \
            --name $WEBAPP \
            --src streamlit.zip
